# Generated by Django 5.2.6 on 2025-09-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., MacBook Pro 13-inch 2020', max_length=200)),
                ('description', models.TextField(help_text='Include specs like RAM, CPU, Storage, Condition, etc.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='laptops/')),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_email', models.EmailField(max_length=254)),
                ('is_approved', models.BooleanField(default=False, help_text='Approved by admin to be shown on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
